### PR TITLE
install littler from CRAN

### PR DESCRIPTION
**Pull request by kevinushey**
cc: @eddelbuettel, is this sufficient for setting up `littler` to be used from the command line?

### CODE REVIEW

**Comment by eddelbuettel** [comment]
The three new lines look good.  Do we have `options("repos")` set at that point?

**Comment by kevinushey** [comment]
Sorry, a little git SNAFU caused a close / re-open. Should be good to go, unless we do need to build `littler` itself with UBSAN?

**Comment by eddelbuettel** [comment]
Good point -- `littler` itself does not need the (UB)SAN settings.  Container itself still works as expected?

**Comment by kevinushey** [comment]
After a little bit of pain and suffering to get docker working on OS X, and a sneaky force-push on the branch, I can confirm all is well. :)

**Comment by eddelbuettel** [comment]
Thanks so much!

**Pull request merged**
