### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by courtiol**
I have only added the library libgdal1-dev, which is needed for rgdal and all packages calling it.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Tricky.  

`libgdal1-dev` is clearly needed for `rgdal` and its reverse dependencies ... but then we don't give all other CRAN packages the same treatment. 

I think this make more sense as a local mod.  You could import this contain and just add the one layer.  Cleaner?

**Comment by courtiol** [comment]
Thanks for the fast reaction.
I am not sure how to do that (new to docker and so far I am not going very
far...), but I could try!
Also, would you be so kind to update the r-devel-san-clang that is no
longer an r-devel at the moment?
Best,
Alex


On 18 January 2016 at 23:31, Dirk Eddelbuettel <notifications@github.com>
wrote:

> Tricky.
>
> libgdal1-dev is clearly needed for rgdal and its reverse dependencies ...
> but then we don't give all other CRAN packages the same treatment.
>
> I think this make more sense as a local mod. You could import this contain
> and just add the one layer. Cleaner?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rocker-org/r-devel-san-clang/pull/3#issuecomment-172671260>
> .
>



-- 
Alexandre Courtiol

http://sites.google.com/site/alexandrecourtiol/home

*"Science is the belief in the ignorance of experts"*, R. Feynman

**Comment by eddelbuettel** [comment]
If you are newer to Docker, the simplest is just to start Docker. I would do 

```
cd ~/some/dir/       # now you are above the directories you need
docker run --rm -ti -v $(pwd):/mnt r-devel-san-clang /bin/bash
```

which starts docker. Then inside of docker
```
cd /mnt                 # now you are above the directories you need
apt-get update
apt-get install libgdal1-dev
```
and you are ready to roll.  You can also look into `docker commit` you preserve the modified container you just created.

**Comment by courtiol** [comment]
Thanks!

On 19 January 2016 at 00:18, Dirk Eddelbuettel <notifications@github.com>
wrote:

> If you are newer to Docker, the simplest is just to start Docker. I would
> do
>
> cd ~/some/dir/       # now you are above the directories you need
> docker run --rm -ti -v $(pwd):/mnt r-devel-san-clang /bin/bash
>
> which starts docker. Then inside of docker
>
> cd /mnt                 # now you are above the directories you need
> apt-get update
> apt-get install libgdal1-dev
>
> and you are ready to roll. You can also look into docker commit you
> preserve the modified container you just created.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rocker-org/r-devel-san-clang/pull/3#issuecomment-172678863>
> .
>



-- 
Alexandre Courtiol

http://sites.google.com/site/alexandrecourtiol/home

*"Science is the belief in the ignorance of experts"*, R. Feynman

**Comment by courtiol** [comment]
One problem is that the library does not install as it does not
automatically install the dependencies for some reason.
Ex: "The following packages have unmet dependencies:
 libgdal1-dev : Depends: libgdal-dev but it is not going to be installed"
and if I try to install the latter it also require others and so one... Do
you know a way to install dependencies automatically within docker?
Thanks


On 19 January 2016 at 10:12, Alexandre Courtiol <
alexandre.courtiol@gmail.com> wrote:

> Thanks!
>
> On 19 January 2016 at 00:18, Dirk Eddelbuettel <notifications@github.com>
> wrote:
>
>> If you are newer to Docker, the simplest is just to start Docker. I would
>> do
>>
>> cd ~/some/dir/       # now you are above the directories you need
>> docker run --rm -ti -v $(pwd):/mnt r-devel-san-clang /bin/bash
>>
>> which starts docker. Then inside of docker
>>
>> cd /mnt                 # now you are above the directories you need
>> apt-get update
>> apt-get install libgdal1-dev
>>
>> and you are ready to roll. You can also look into docker commit you
>> preserve the modified container you just created.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/rocker-org/r-devel-san-clang/pull/3#issuecomment-172678863>
>> .
>>
>
>
>
> --
> Alexandre Courtiol
>
> http://sites.google.com/site/alexandrecourtiol/home
>
> *"Science is the belief in the ignorance of experts"*, R. Feynman
>



-- 
Alexandre Courtiol

http://sites.google.com/site/alexandrecourtiol/home

*"Science is the belief in the ignorance of experts"*, R. Feynman

**Comment by courtiol** [comment]
This is what I have done so far but it still does not work...
I tried things around this without success either.

sudo docker run --rm -ti -v $(pwd):/mnt rocker/r-devel-ubsan-clang
/bin/bash

cd /mnt

echo "deb http://ftp.de.debian.org/debian/ jessie non-free contrib main" >
/etc/apt/sources.list
echo "deb-src http://ftp.de.debian.org/debian/ jessie non-free contrib
main" >> /etc/apt/sources.list
echo "deb http://ftp.de.debian.org/debian/ jessie-updates main contrib
non-free" >> /etc/apt/sources.list
echo "deb-src http://ftp.de.debian.org/debian/ jessie-updates main contrib
non-free" >> /etc/apt/sources.list

apt-get -y update
apt-get build-dep libgdal-dev # does not work because some library are too
recent...

HERE is the output:

Reading package lists... Done
Building dependency tree
Reading state information... Done
Picking 'gdal' as source package instead of 'libgdal-dev'
Selected version '1.10.1+dfsg-8' (jessie) for gdal
The following packages have unmet dependencies:
 libcurl4-gnutls-dev : Depends: libcurl3-gnutls (= 7.38.0-4+deb8u2) but
7.46.0-1 is to be installed
 libopenjpeg-dev : Depends: libopenjpeg5 (= 1:1.5.2-3) but 1:1.5.2-3.1 is
to be installed
 libpq-dev : Depends: libssl-dev but it is not going to be installed
             Depends: krb5-multidev but it is not going to be installed
 libsqlite3-dev : Depends: libsqlite3-0 (= 3.8.7.1-1+deb8u1) but 3.10.1-1
is to be installed
 libxml2-dev : Depends: libxml2 (= 2.9.1+dfsg1-5) but 2.9.2+dfsg1-3 is to
be installed
 python-all-dev : Depends: libpython-all-dev (= 2.7.9-1) but it is not
going to be installed
                  Depends: python-dev (= 2.7.9-1) but it is not going to be
installed
                  Depends: python2.7-dev (>= 2.7-7) but it is not going to
be installed
E: Build-dependencies for libgdal-dev could not be satisfied.


On 19 January 2016 at 11:10, Alexandre Courtiol <
alexandre.courtiol@gmail.com> wrote:

> One problem is that the library does not install as it does not
> automatically install the dependencies for some reason.
> Ex: "The following packages have unmet dependencies:
>  libgdal1-dev : Depends: libgdal-dev but it is not going to be installed"
> and if I try to install the latter it also require others and so one... Do
> you know a way to install dependencies automatically within docker?
> Thanks
>
>
> On 19 January 2016 at 10:12, Alexandre Courtiol <
> alexandre.courtiol@gmail.com> wrote:
>
>> Thanks!
>>
>> On 19 January 2016 at 00:18, Dirk Eddelbuettel <notifications@github.com>
>> wrote:
>>
>>> If you are newer to Docker, the simplest is just to start Docker. I
>>> would do
>>>
>>> cd ~/some/dir/       # now you are above the directories you need
>>> docker run --rm -ti -v $(pwd):/mnt r-devel-san-clang /bin/bash
>>>
>>> which starts docker. Then inside of docker
>>>
>>> cd /mnt                 # now you are above the directories you need
>>> apt-get update
>>> apt-get install libgdal1-dev
>>>
>>> and you are ready to roll. You can also look into docker commit you
>>> preserve the modified container you just created.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/rocker-org/r-devel-san-clang/pull/3#issuecomment-172678863>
>>> .
>>>
>>
>>
>>
>> --
>> Alexandre Courtiol
>>
>> http://sites.google.com/site/alexandrecourtiol/home
>>
>> *"Science is the belief in the ignorance of experts"*, R. Feynman
>>
>
>
>
> --
> Alexandre Courtiol
>
> http://sites.google.com/site/alexandrecourtiol/home
>
> *"Science is the belief in the ignorance of experts"*, R. Feynman
>



-- 
Alexandre Courtiol

http://sites.google.com/site/alexandrecourtiol/home

*"Science is the belief in the ignorance of experts"*, R. Feynman

**Comment by eddelbuettel** [comment]
Please learn to properly format your message. On the web UI at https://github.com/rocker-org/r-devel-san-clang/pull/3 where I read this, it only came through as two lines.

You are expecting free help from me, make it easier for me to help you.

In short, I'd try 

```
apt-get -t unstable install libgdal-dev 
```

to force newer library, and to use `install`, not `build-dep` -- which is what I told you earlier.

You are now at a state where we are discussing basic steps of using a Debian or Ubuntu system.  This is not the right forum for that type of help.  Try a proper mailing list, or a StackExchange site like superuser.

**Comment by eddelbuettel** [comment]
And the answer to 

>Ex: "The following packages have unmet dependencies:
 libgdal1-dev : Depends: libgdal-dev but it is not going to be installed"

is usually to include both

```
apt-get install libgdal1-dev libgdal-dev
```

Seems like there was a renaming.

**Comment by courtiol** [comment]
The apt-get -t unstable install ... did the trick!
(apt-get -t unstable install libgdal-dev libgdal1-dev libproj-dev libgfortran-4.9-dev)
That plus changing Debian's mirrors as they kept closing my connection remotely preventing library downloads (I guess my too many trials made them believe I was some kind of robot...).
I still wonder why check.r tells sanitizer problems when run in shell but not when run directly within R, which makes debugging difficult, but the problem is now solved!
Thank you so much!

**Comment by eddelbuettel** [comment]
Excellent, glad to hear it helped.

**Pull request closed without merging**
