### PR TITLE
Detect stack use after scope

### PR DESCRIPTION
**Pull request by krlmlr**
Only this setting detects a dplyr problem that is particularly difficult to find in the source code, see the links in https://github.com/tidyverse/dplyr/pull/3098. The issue itself materializes only with very aggressive optimization settings with clang.

A simplified self-contained version of the problem can be found at https://stackoverflow.com/q/46233852/946850. I fond this particular switch `-fsanitize-address-use-after-scope` in https://stackoverflow.com/a/42342428/946850. Indeed, my simplified problem evades detection without `-fsanitize-address-use-after-scope`.

CC @hadley @lionel- @gaborcsardi.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
When I saw the title I was already thinking "nice but what about an example tickling this" for the sanitizers package (so that we can check future builds).   Do you think you can construct one (as a PR to sanitziers, say) ?

**Comment by krlmlr** [comment]
Thanks. My SO example is pretty self-contained, just replace `main()` with an entry point reachable from R and change/remove the `cerr` output. I need to handle a few other things first.

**Comment by krlmlr** [comment]
Happy to add installation for `llvm-symbolizer` to this PR (or to a separate PR) though, this is necessary for proper stack traces.

**Comment by eddelbuettel** [comment]
Will take a look, thanks.

**Comment by eddelbuettel** [comment]
Sorry, what was that about `llvm-symbolizer`?  Is is a "must have" for this to work?  A "nice to have"?

**Comment by krlmlr** [comment]
A "very nice to have", turning addresses into symbolic references in the stack trace.

**Comment by eddelbuettel** [comment]
I saw man page reference for it.  Was this once part of the (Debian or Ubuntu) llvm package but is no more?  So would it be a small-ish in `/usr/local/bin` ?

**Comment by krlmlr** [comment]
Yeah, I needed to install `llvm-4.0` too.

**Comment by krlmlr** [comment]
I added it, and two libs I keep installing again and again when running my tests.

**Pull request merged**
